### ISSUE TITLE
Change theme btn isn't working

### ISSUE THREAD

**Issue by Devang47** [asrvd/asrvd.me#1]
![Screenshot 2022-10-24 at 4 00 10 PM](https://user-images.githubusercontent.com/72780418/197506446-34136766-c8a7-4b47-8443-ddfe655f3831.JPG)

**Comment by asrvd** [comment]
yes, I haven't implemented light theme yet, working on it

**Comment by asrvd** [comment]
implemented in https://github.com/asrvd/asrvd.me/commit/20998cd72e92c5ab1805ce88cb18a4db45698a1b
